# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aholtzma <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/11 16:46:04 by aholtzma          #+#    #+#              #
#    Updated: 2019/04/11 16:49:47 by aholtzma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCE = main.c
CC = gcc
FLAGS = -Wall -Werror -Wextra -o
EXEC = ft_display_file

all:
	$(CC) $(SOURCE) $(FLAGS) $(EXEC)

clean:
	rm -rf *.o

fclean: clean
	rm -rf $(EXEC) 
