# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aholtzma <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/11 18:17:54 by aholtzma          #+#    #+#              #
#    Updated: 2019/04/11 18:21:16 by aholtzma         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCE = ft_display_file.c main.c
CC = gcc
FLAGS = -Wall -Werror -Wextra -o
EXEC = ft_cat

all:
	$(CC) $(SOURCE) $(FLAGS) $(EXEC)
clean:
	rm -f $(EXEC)
fclean: clean
